- Make all runners work with paths and/or files with spaces in them # See also http://wooledge.org:8000/BashFAQ
git-svn-id: svn+ssh://svn.xp-framework.net/home/svn/xpforge/trunk/experiments@10322 d2cacbed-c0f6-0310-851a-9dad52fc623a

diff --git a/arena/xprt/sh/xprt b/arena/xprt/sh/xprt
--- a/arena/xprt/sh/xprt
+++ b/arena/xprt/sh/xprt
@@ -30,8 +30,8 @@ add_path_file () {
   local base="$1"
   local file="$2"
   local includes=""
-  
-  for l in `grep -v ^# $file` ; do
+
+  for l in `grep -v ^# "$file"` ; do
     includes=$includes$(translate_path "$base" "$l")$PATHSEP
   done
   
@@ -46,22 +46,34 @@ scan_path_files() {
     return ""; 
   fi
   
-  for i in `ls "$dir"/*.pth 2>/dev/null` ; do
-    includes=$includes$(add_path_file "$dir" "$i")
-  done
-  
-  echo $includes
+  ls "$dir"/*.pth 2>/dev/null | (
+    while read i ; do
+      includes=$includes$(add_path_file "$dir" "$i")
+    done
+    echo $includes
+  )
 }
 
 execute() {
   local base="$1"
   local runner="$2"
   local include="$3"
+  local xppath="$1"
+  local ifs="|"
 
-  local includes=$(scan_path_files "$base")
+  for line in `cat "$base"/xp.ini` ; do
+    case "$line" in
+      use=*)
+        value=${line#*=}
+        xppath=$(translate_path "$base" "$value")
+      ;;
+    esac
+  done
 
-  if [ -z $includes ] ; then
-    echo "*** Error loading boot class path in $base" >&2;
+  local includes=$(scan_path_files "$xppath")
+
+  if [ -z "$includes" ] ; then
+    echo "*** Error loading boot class path in $xppath" >&2;
     return 1
   fi
   
@@ -78,9 +90,9 @@ execute() {
   
   config=""
   executor="php"
-  args="-dinclude_path=\"$includes\" -dmagic_quotes_gpc=0"
-  if [ -e "$base"/php.ini ] ; then
-    for line in `cat "$base"/php.ini` ; do
+  args="-dinclude_path=\"$includes\"${ifs}-dmagic_quotes_gpc=0"
+  if [ -e "$xppath"/php.ini ] ; then
+    for line in `cat "$xppath"/php.ini` ; do
       case "$line" in
         *=*)
           key=${line%=*}
@@ -88,12 +100,12 @@ execute() {
           if [ "executor" = "$key" ]; then
             executor="$value"
           else 
-            args="$args -d$key=\"$value\""
+            args="$args${ifs}-d$key=\"$value\""
           fi
         ;;
       esac
     done
   fi
-  
-  echo "$executor $args $(translate_path "$base" ".")$DIRSEP$runner.php"
+
+  echo ${executor}${ifs}${args}${ifs}$(translate_path "$xppath"/bin ".")${runner}".php"
 }
